// Auto-generated from MD files - do not edit manually
// Generated at: 2026-02-04T14:13:50.099Z

export const METAMODEL = {
  "groups": [
    {
      "name": "01_preferences",
      "description": "# 1.PREF - Настройки и предпочтения\n\nНастраиваемые параметры стажёра: цели, роли, расписание, план развития\n\n## Contains\n\n- `objective` - Цели обучения\n- `role_set` - Текущие роли\n- `domain_focus` - Интересующие области\n- `daily_task_time` - Время получения задания\n- `daily_report_time` - Время отчёта за день\n- `weekly_analytics_time` - Время получения аналитики\n- `strategy_request_time` - Время запроса стратегирования\n- `target_state` - Целевые показатели состояния\n- `guide_track_set` - Выбранные руководства\n- `weekly_section` - Раздел руководства к изучению\n- `weekly_time_budget` - Недельный бюджет времени\n- `planned_time_tomorrow` - Планируемое время на завтра\n- `highlighted_methods` - Фокусные методы\n- `stage_end_date` - Дата окончания ближайшего этапа\n- `current_problems` - Текущие проблемы\n- `dissatisfactions` - Мои неудовлетворенности\n- `emotions` - Мои эмоции и чувства\n- `priority_projects` - Мои приоритетные проекты\n- `stage_target_result` - Планируемый результат ближайшего этапа\n- `weekly_work_products` - Рабочие продукты на неделю\n",
      "indicators": {
        "01_Текущие проблемы": "# IND.1.PREF.current_problems\n\n**Name:** Текущие проблемы\n**Name (EN):** Current problems\n**Type:** semantic\n**Format:** list[string]\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "02_Время отчёта за день": "# IND.1.PREF.daily_report_time\n\n**Name:** Время отчёта за день\n**Name (EN):** Daily report time\n**Type:** structural\n**Format:** time\n**Unit:** HH:MM\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "03_Время получения задания": "# IND.1.PREF.daily_task_time\n\n**Name:** Время получения задания\n**Name (EN):** Daily task time\n**Type:** structural\n**Format:** time\n**Unit:** HH:MM\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "04_Мои неудовлетворенности": "# IND.1.PREF.dissatisfactions\n\n**Name:** Мои неудовлетворенности\n**Name (EN):** My dissatisfactions\n**Type:** semantic\n**Format:** list[string]\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "05_Интересующие области": "# IND.1.PREF.domain_focus\n\n**Name:** Интересующие области\n**Name (EN):** Domain focus\n**Type:** semantic\n**Format:** list[string]\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "06_Мои эмоции и чувства": "# IND.1.PREF.emotions\n\n**Name:** Мои эмоции и чувства\n**Name (EN):** My emotions and feelings\n**Type:** semantic\n**Format:** list[string]\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "07_Выбранные руководства": "# IND.1.PREF.guide_track_set\n\n**Name:** Выбранные руководства\n**Name (EN):** Selected guides\n**Type:** semantic\n**Format:** list[string]\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "08_Фокусные методы": "# IND.1.PREF.highlighted_methods\n\n**Name:** Фокусные методы\n**Name (EN):** Highlighted methods\n**Type:** semantic\n**Format:** list[string]\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "09_Цели обучения": "# IND.1.PREF.objective\n\n**Name:** Цели обучения\n**Name (EN):** Learning objectives\n**Type:** semantic\n**Format:** structured_text\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "10_Планируемое время на завтра": "# IND.1.PREF.planned_time_tomorrow\n\n**Name:** Планируемое время на завтра\n**Name (EN):** Planned time tomorrow\n**Type:** temporal\n**Format:** float\n**Unit:** hours\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "11_Мои приоритетные проекты": "# IND.1.PREF.priority_projects\n\n**Name:** Мои приоритетные проекты\n**Name (EN):** My priority projects\n**Type:** semantic\n**Format:** list[string]\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "12_Текущие роли": "# IND.1.PREF.role_set\n\n**Name:** Текущие роли\n**Name (EN):** Current roles\n**Type:** semantic\n**Format:** list[string]\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "13_Дата окончания ближайшего этапа": "# IND.1.PREF.stage_end_date\n\n**Name:** Дата окончания ближайшего этапа\n**Name (EN):** Stage end date\n**Type:** temporal\n**Format:** date\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "14_Планируемый результат ближайшего этапа": "# IND.1.PREF.stage_target_result\n\n**Name:** Планируемый результат ближайшего этапа\n**Name (EN):** Planned stage result\n**Type:** semantic\n**Format:** structured_text\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "15_Время запроса стратегирования": "# IND.1.PREF.strategy_request_time\n\n**Name:** Время запроса стратегирования\n**Name (EN):** Strategy request time\n**Type:** structural\n**Format:** day_time\n**Unit:** day_of_week + HH:MM\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "16_Целевые показатели состояния": "# IND.1.PREF.target_state\n\n**Name:** Целевые показатели состояния\n**Name (EN):** Target state indicators\n**Type:** scale\n**Format:** object\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n\n## Schema\n```json\n{\n  \"energy\": \"1-5\",\n  \"attention\": \"1-5\",\n  \"sleep\": \"1-5\"\n}\n```\n",
        "17_Время получения аналитики": "# IND.1.PREF.weekly_analytics_time\n\n**Name:** Время получения аналитики\n**Name (EN):** Weekly analytics time\n**Type:** structural\n**Format:** day_time\n**Unit:** day_of_week + HH:MM\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "18_Раздел руководства к изучению": "# IND.1.PREF.weekly_section\n\n**Name:** Раздел руководства к изучению\n**Name (EN):** Weekly guide section\n**Type:** semantic\n**Format:** string\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "19_Недельный бюджет времени": "# IND.1.PREF.weekly_time_budget\n\n**Name:** Недельный бюджет времени\n**Name (EN):** Weekly time budget\n**Type:** temporal\n**Format:** float\n**Unit:** hours/week\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n",
        "20_Рабочие продукты на неделю": "# IND.1.PREF.weekly_work_products\n\n**Name:** Рабочие продукты на неделю\n**Name (EN):** Weekly work products\n**Type:** semantic\n**Format:** list[string]\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n"
      }
    },
    {
      "name": "02_agency",
      "description": "# 2.1 - Агентность и учебный ритм\n\nВремя, регулярность, стабильность слотов, срывы\n\n## Contains\n\n- `1` - Среднее число часов саморазвития в неделю\n- `2` - Доля дней со слотом (регулярность)\n- `4` - Стабильность слотов (серии дней подряд)\n- `5` - Частота срывов\n- `7` - Индекс инициативности (регулярность стратегирования)\n",
      "indicators": {
        "01_Среднее число часов саморазвития в неделю": "# IND.2.1.1\n\n**Name:** Среднее число часов саморазвития в неделю\n**Name (EN):** Average self-development hours per week\n**Type:** temporal\n**Format:** float\n**Unit:** hours/week\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"max\": 0.5,\n    \"period_weeks\": 1\n  },\n  \"STG.Student.Practicing\": {\n    \"min\": 4,\n    \"period_weeks\": 4\n  },\n  \"STG.Student.Systematic\": {\n    \"min\": 6,\n    \"period_weeks\": 8\n  },\n  \"STG.Student.Disciplined\": {\n    \"min\": 8,\n    \"period_weeks\": 12\n  },\n  \"STG.Student.Proactive\": {\n    \"min\": 10,\n    \"period_weeks\": 24\n  }\n}\n```\n",
        "02_Доля дней со слотом (регулярность)": "# IND.2.1.2\n\n**Name:** Доля дней со слотом (регулярность)\n**Name (EN):** Proportion of days with learning slot\n**Type:** frequency\n**Format:** float\n**Unit:** days/week\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": 1,\n    \"period_weeks\": 1\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": 3,\n    \"period_weeks\": 4\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": 5,\n    \"period_weeks\": 8\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": 6,\n    \"period_weeks\": 12\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": 6.7,\n    \"period_weeks\": 24\n  }\n}\n```\n",
        "03_Стабильность слотов (серии дней подряд)": "# IND.2.1.4\n\n**Name:** Стабильность слотов (серии дней подряд)\n**Name (EN):** Slot stability (consecutive days)\n**Type:** frequency\n**Format:** integer\n**Unit:** consecutive_days\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": 0,\n    \"period_weeks\": 1\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": 3,\n    \"period_weeks\": 4\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": 4,\n    \"period_weeks\": 8\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": 5,\n    \"period_weeks\": 12\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": 6,\n    \"period_weeks\": 24\n  }\n}\n```\n",
        "04_Частота срывов": "# IND.2.1.5\n\n**Name:** Частота срывов\n**Name (EN):** Relapse frequency\n**Type:** frequency\n**Format:** string\n**Unit:** relapses/period\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": null\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": \"1 срыв в 2 недели\"\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": \"1 срыв в месяц\"\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": \"Нет срывов\"\n  }\n}\n```\n",
        "05_Индекс инициативности (регулярность стратегирования)": "# IND.2.1.7\n\n**Name:** Индекс инициативности (регулярность стратегирования)\n**Name (EN):** Initiative index (strategy regularity)\n**Type:** frequency\n**Format:** float\n**Unit:** percent_weeks\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": 0,\n    \"period_weeks\": 1\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": 0,\n    \"period_weeks\": 4\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": 0,\n    \"period_weeks\": 8\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": 80,\n    \"period_weeks\": 12\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": 95,\n    \"period_weeks\": 24\n  }\n}\n```\n"
      }
    },
    {
      "name": "03_mastery",
      "description": "# 2.2 - Степень мастерства\n\nИнтенсивность практики, рабочие продукты, мировоззрение, привычки\n\n## Contains\n\n- `1` - Интенсивность практики (степень мастерства по практикам)\n- `6` - Индекс рабочих продуктов (творческий конвейер)\n- `8` - Учтённое время (прохождение ритуала)\n- `9` - Развитие мировоззрения\n- `10` - Трансформация привычек\n- `11` - Развитие потенциала\n- `12` - Текущие негативные привычки\n",
      "indicators": {
        "01_Интенсивность практики (степень мастерства по практикам)": "# IND.2.2.1\n\n**Name:** Интенсивность практики (степень мастерства по практикам)\n**Name (EN):** Practice intensity (mastery levels)\n**Type:** categorical\n**Format:** checklist\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": null\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": \"Чек-листы: Объяснение 75%, Умение 50%\"\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": \"Чек-листы: Умение 75%, Навык 50%\"\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": \"Чек-листы: Навык 75%, Мастерство 50%\"\n  }\n}\n```\n",
        "02_Индекс рабочих продуктов (творческий конвейер)": "# IND.2.2.6\n\n**Name:** Индекс рабочих продуктов (творческий конвейер)\n**Name (EN):** Work products index (creative pipeline)\n**Type:** frequency\n**Format:** float\n**Unit:** drafts/week\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": 0,\n    \"period_weeks\": 1\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": 0,\n    \"period_weeks\": 4\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": 1,\n    \"period_weeks\": 8\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": 1.5,\n    \"period_weeks\": 12\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": 2,\n    \"period_weeks\": 24\n  }\n}\n```\n",
        "03_Учтённое время (прохождение ритуала)": "# IND.2.2.8\n\n**Name:** Учтённое время (прохождение ритуала)\n**Name (EN):** Accounted time (ritual completion)\n**Type:** temporal\n**Format:** float\n**Unit:** hours/week\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": 0,\n    \"period_weeks\": 1\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": 0,\n    \"period_weeks\": 4\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": 20,\n    \"period_weeks\": 8\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": 30,\n    \"period_weeks\": 12\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": 40,\n    \"period_weeks\": 24\n  }\n}\n```\n",
        "04_Развитие мировоззрения": "# IND.2.2.9\n\n**Name:** Развитие мировоззрения\n**Name (EN):** Worldview evolution\n**Type:** semantic\n**Format:** checklist\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": \"Понимаю зачем, чему, как и когда учиться\"\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": \"Понимаю что такое мировоззрение и замечаю свои мемы\"\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": \"Поменял как минимум один свой плохой мем\"\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": \"Разобрался с большинством плохих мемов и помогаю другим\"\n  }\n}\n```\n",
        "05_Трансформация привычек": "# IND.2.2.10\n\n**Name:** Трансформация привычек\n**Name (EN):** Habit transformation\n**Type:** semantic\n**Format:** string\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": null\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": null\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": \"Осознаю свои плохие привычки и начал работать\"\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": \"Отказался или заменил плохую привычку на хорошую\"\n  }\n}\n```\n",
        "06_Развитие потенциала": "# IND.2.2.11\n\n**Name:** Развитие потенциала\n**Name (EN):** Potential growth\n**Type:** semantic\n**Format:** string\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": null\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": null\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": \"Понимаю характеристику агента и потенциал\"\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": \"Повысил потенциал хотя бы по одной характеристике\"\n  }\n}\n```\n",
        "07_Текущие негативные привычки": "# IND.2.2.12\n\n**Name:** Текущие негативные привычки\n**Name (EN):** Current negative habits\n**Type:** semantic\n**Format:** list[string]\n\n## Flags\n- for_prompts: false\n- for_qualification: false\n- trainee_model: false\n"
      }
    },
    {
      "name": "04_characteristics",
      "description": "# 2.3 - Характеристики по ступеням\n\nРефлексия, окружение, паттерны поведения, мемы\n\n## Contains\n\n- `2` - Индекс рефлексии (частота заметок)\n- `4` - Характеристики окружения (контроль инфопотока)\n- `7` - Поведенческие паттерны\n- `8` - Текущие мемы (продуктивные и непродуктивные)\n- `9` - Калибр личности (системные уровни целей)\n",
      "indicators": {
        "01_Индекс рефлексии (частота заметок)": "# IND.2.3.2\n\n**Name:** Индекс рефлексии (частота заметок)\n**Name (EN):** Reflection index (notes frequency)\n**Type:** frequency\n**Format:** float\n**Unit:** notes/week\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": 0,\n    \"period_weeks\": 1\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": 0,\n    \"period_weeks\": 4\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": 5,\n    \"period_weeks\": 8\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": 6,\n    \"period_weeks\": 12\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": 6.7,\n    \"period_weeks\": 24\n  }\n}\n```\n",
        "02_Характеристики окружения (контроль инфопотока)": "# IND.2.3.4\n\n**Name:** Характеристики окружения (контроль инфопотока)\n**Name (EN):** Environment characteristics (infostream control)\n**Type:** semantic\n**Format:** checklist\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": \"Начал чистить окружение (убрал лишние каналы)\"\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": \"Взял под контроль внимание, осознанно меняю окружение\"\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": \"Стал активным участником сообщества\"\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": \"Активно занимается просвещением\"\n  }\n}\n```\n",
        "03_Поведенческие паттерны": "# IND.2.3.7\n\n**Name:** Поведенческие паттерны\n**Name (EN):** Behavior patterns\n**Type:** categorical\n**Format:** string\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": null\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": \"Выявляет и старается обходить\"\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": \"Снижает/перепрошивает\"\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": \"Переписывает сознательно\"\n  }\n}\n```\n",
        "04_Текущие мемы (продуктивные и непродуктивные)": "# IND.2.3.8\n\n**Name:** Текущие мемы (продуктивные и непродуктивные)\n**Name (EN):** Current memes\n**Type:** semantic\n**Format:** string\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": null\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": \"Замечает мемы у других\"\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": \"Замечает свои непродуктивные мемы\"\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": \"Осознанно меняет\"\n  }\n}\n```\n",
        "05_Калибр личности (системные уровни целей)": "# IND.2.3.9\n\n**Name:** Калибр личности (системные уровни целей)\n**Name (EN):** Personality caliber (systemic intent levels)\n**Type:** semantic\n**Format:** string\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": null\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": null\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": null\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": \"Уровень команды и сообщества\"\n  }\n}\n```\n"
      }
    },
    {
      "name": "05_qualification",
      "description": "# 2.4 - Квалификация\n\nТекущая ступень, история переходов, критерии присвоения\n\n## Contains\n\n- `2` - Внутренняя ступень Ученика\n- `3` - История смены ступеней\n- `7` - Дата последнего присвоения\n- `8` - Критерии присвоения ступени\n",
      "indicators": {
        "01_Внутренняя ступень Ученика": "# IND.2.4.2\n\n**Name:** Внутренняя ступень Ученика\n**Name (EN):** Internal student stage\n**Type:** categorical\n**Format:** enum\n\n## Flags\n- for_prompts: true\n- for_qualification: true\n- trainee_model: true\n\n## Enum Values\n```json\n[\n  \"STG.Student.Random\",\n  \"STG.Student.Practicing\",\n  \"STG.Student.Systematic\",\n  \"STG.Student.Disciplined\",\n  \"STG.Student.Proactive\"\n]\n```\n",
        "02_История смены ступеней": "# IND.2.4.3\n\n**Name:** История смены ступеней\n**Name (EN):** Stage change history\n**Type:** categorical\n**Format:** list[object]\n\n## Flags\n- for_prompts: true\n- for_qualification: true\n- trainee_model: true\n",
        "03_Дата последнего присвоения": "# IND.2.4.7\n\n**Name:** Дата последнего присвоения\n**Name (EN):** Last assigned date\n**Type:** temporal\n**Format:** date\n\n## Flags\n- for_prompts: true\n- for_qualification: true\n- trainee_model: true\n",
        "04_Критерии присвоения ступени": "# IND.2.4.8\n\n**Name:** Критерии присвоения ступени\n**Name (EN):** Qualification criteria snapshot\n**Type:** semantic\n**Format:** structured_text\n**Description:** Срез показателей на дату присвоения квалификации\n\n## Flags\n- for_prompts: true\n- for_qualification: true\n- trainee_model: true\n"
      }
    },
    {
      "name": "06_roles",
      "description": "# 2.5 - Мастерство по ролям\n\nРолевой профиль, индексы по ролям (Ученик, Интеллектуал, Профессионал)\n\n## Contains\n\n- `1` - Мастерство в целевых ролях\n- `2` - Прогресс по ролевым чек-листам\n- `3` - Применение ролей в проектах\n",
      "indicators": {
        "01_Мастерство в целевых ролях": "# IND.2.5.1\n\n**Name:** Мастерство в целевых ролях\n**Name (EN):** Target role mastery\n**Type:** categorical\n**Format:** object\n\n## Flags\n- for_prompts: true\n- for_qualification: true\n- trainee_model: true\n\n## Schema\n```json\n{\n  \"role\": \"string\",\n  \"level\": \"enum[Знакомство,Объяснение,Умение,Навык,Мастерство]\"\n}\n```\n",
        "02_Прогресс по ролевым чек-листам": "# IND.2.5.2\n\n**Name:** Прогресс по ролевым чек-листам\n**Name (EN):** Role checklist progress\n**Type:** frequency\n**Format:** float\n**Unit:** percent\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n",
        "03_Применение ролей в проектах": "# IND.2.5.3\n\n**Name:** Применение ролей в проектах\n**Name (EN):** Role application in projects\n**Type:** frequency\n**Format:** integer\n**Unit:** projects\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n"
      }
    },
    {
      "name": "07_resourcefulness",
      "description": "# 2.6 - Ресурсность и устойчивость\n\nСостояние, ритм, восстановление, гибкость пересборки\n\n## Contains\n\n- `1` - Индекс ресурсности (продуктивность состояния)\n- `3` - Ритм работа–отдых (соблюдение ритма)\n- `4` - Устойчивость к сбоям (скорость восстановления)\n- `5` - Управление текущим состоянием\n- `6` - Частота методов восстановления\n- `7` - Использованные методы поддержки\n- `8` - Гибкость пересборки\n",
      "indicators": {
        "01_Индекс ресурсности (продуктивность состояния)": "# IND.2.6.1\n\n**Name:** Индекс ресурсности (продуктивность состояния)\n**Name (EN):** Resourcefulness index (state productivity)\n**Type:** scale\n**Format:** float\n**Unit:** 1-5\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": null\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": 3,\n    \"period_weeks\": 8\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": 3.7,\n    \"period_weeks\": 12\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": 4.3,\n    \"period_weeks\": 24\n  }\n}\n```\n",
        "02_Ритм работа–отдых (соблюдение ритма)": "# IND.2.6.3\n\n**Name:** Ритм работа–отдых (соблюдение ритма)\n**Name (EN):** Work-rest rhythm adherence\n**Type:** scale\n**Format:** string\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": null\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": \"3–4 дня в ритме/неделя\"\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": \"6–7 дней стабильно\"\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": \"Автоматизированный ритм\"\n  }\n}\n```\n",
        "03_Устойчивость к сбоям (скорость восстановления)": "# IND.2.6.4\n\n**Name:** Устойчивость к сбоям (скорость восстановления)\n**Name (EN):** Fault tolerance (recovery speed)\n**Type:** temporal\n**Format:** integer\n**Unit:** days\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": null\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": 7\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": 3\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": 1\n  }\n}\n```\n",
        "04_Управление текущим состоянием": "# IND.2.6.5\n\n**Name:** Управление текущим состоянием\n**Name (EN):** Current state regulation\n**Type:** scale\n**Format:** float\n**Unit:** 1-5\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": null\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": null\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": 3,\n    \"period_weeks\": 12\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": 3.5,\n    \"period_weeks\": 24\n  }\n}\n```\n",
        "05_Частота методов восстановления": "# IND.2.6.6\n\n**Name:** Частота методов восстановления\n**Name (EN):** Recovery methods frequency\n**Type:** frequency\n**Format:** string\n**Unit:** times/week\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": null\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": \"1–2 метода в неделю\"\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": \"Стабильные практики\"\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": \"Саморегуляция в рутине\"\n  }\n}\n```\n",
        "06_Использованные методы поддержки": "# IND.2.6.7\n\n**Name:** Использованные методы поддержки\n**Name (EN):** Support methods used\n**Type:** frequency\n**Format:** string\n**Unit:** count/week\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": null\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": \"1–2 регулярных практики\"\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": \"3–5 встроенных в рутину\"\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": \"Комплексная система поддержки\"\n  }\n}\n```\n",
        "07_Гибкость пересборки": "# IND.2.6.8\n\n**Name:** Гибкость пересборки\n**Name (EN):** Restructuring flexibility\n**Type:** semantic\n**Format:** string\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": null\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": null\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": \"Переосмысливает раз в неделю\"\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": \"Быстро корректирует план\"\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": \"Перестраивает маршрут мгновенно\"\n  }\n}\n```\n"
      }
    },
    {
      "name": "08_community",
      "description": "# 2.7 - Сообщество и вклад\n\nАктивность в клубе, менторство, вклад в культуру\n\n## Contains\n\n- `1` - Активность в сообществе\n- `2` - Помощь другим участникам\n- `3` - Публикации и вклад в контент\n",
      "indicators": {
        "01_Активность в сообществе": "# IND.2.7.1\n\n**Name:** Активность в сообществе\n**Name (EN):** Community activity\n**Type:** frequency\n**Format:** integer\n**Unit:** interactions/week\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n\n## Thresholds\n```json\n{\n  \"STG.Student.Random\": {\n    \"value\": 0\n  },\n  \"STG.Student.Practicing\": {\n    \"value\": 1\n  },\n  \"STG.Student.Systematic\": {\n    \"value\": 3\n  },\n  \"STG.Student.Disciplined\": {\n    \"value\": 5\n  },\n  \"STG.Student.Proactive\": {\n    \"value\": 10\n  }\n}\n```\n",
        "02_Помощь другим участникам": "# IND.2.7.2\n\n**Name:** Помощь другим участникам\n**Name (EN):** Help to other members\n**Type:** frequency\n**Format:** integer\n**Unit:** helps/month\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n",
        "03_Публикации и вклад в контент": "# IND.2.7.3\n\n**Name:** Публикации и вклад в контент\n**Name (EN):** Publications and content contribution\n**Type:** frequency\n**Format:** integer\n**Unit:** posts/month\n\n## Flags\n- for_prompts: false\n- for_qualification: true\n- trainee_model: false\n"
      }
    },
    {
      "name": "09_economics",
      "description": "# 2.8 - Экономика участия\n\nПлатёжная вовлечённость, удержание, ценность/затраты\n\n## Contains\n\n- `1` - Статус подписки\n- `2` - Реферальная активность\n- `3` - Срок участия в программе\n",
      "indicators": {
        "01_Статус подписки": "# IND.2.8.1\n\n**Name:** Статус подписки\n**Name (EN):** Subscription status\n**Type:** categorical\n**Format:** enum\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n\n## Enum Values\n```json\n[\n  \"free\",\n  \"basic\",\n  \"pro\",\n  \"enterprise\"\n]\n```\n",
        "02_Реферальная активность": "# IND.2.8.2\n\n**Name:** Реферальная активность\n**Name (EN):** Referral activity\n**Type:** frequency\n**Format:** integer\n**Unit:** referrals\n\n## Flags\n- for_prompts: false\n- for_qualification: false\n- trainee_model: false\n",
        "03_Срок участия в программе": "# IND.2.8.3\n\n**Name:** Срок участия в программе\n**Name (EN):** Program tenure\n**Type:** temporal\n**Format:** integer\n**Unit:** months\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: true\n"
      }
    },
    {
      "name": "10_ai_usage",
      "description": "# 2.9 - Использование ИИ\n\nВзаимодействие с ИИ, глубина работы\n\n## Contains\n\n- `1` - Использование AI Guide\n- `2` - Качество взаимодействия с ИИ\n- `3` - Применение рекомендаций ИИ\n",
      "indicators": {
        "01_Использование AI Guide": "# IND.2.9.1\n\n**Name:** Использование AI Guide\n**Name (EN):** AI Guide usage\n**Type:** frequency\n**Format:** integer\n**Unit:** sessions/week\n\n## Flags\n- for_prompts: false\n- for_qualification: false\n- trainee_model: false\n",
        "02_Качество взаимодействия с ИИ": "# IND.2.9.2\n\n**Name:** Качество взаимодействия с ИИ\n**Name (EN):** AI interaction quality\n**Type:** scale\n**Format:** float\n**Unit:** 1-5\n\n## Flags\n- for_prompts: false\n- for_qualification: false\n- trainee_model: false\n",
        "03_Применение рекомендаций ИИ": "# IND.2.9.3\n\n**Name:** Применение рекомендаций ИИ\n**Name (EN):** AI recommendations adoption\n**Type:** frequency\n**Format:** float\n**Unit:** percent\n\n## Flags\n- for_prompts: false\n- for_qualification: false\n- trainee_model: false\n"
      }
    },
    {
      "name": "11_integral",
      "description": "# 2.10 - Интегральные профили\n\nПрофиль застревания, риск выгорания, подмена деятельности\n\n## Contains\n\n- `1` - Интегральный индекс агентности\n- `2` - Готовность к следующей ступени\n- `3` - Профиль сильных сторон\n- `4` - Профиль зон развития\n",
      "indicators": {
        "01_Интегральный индекс агентности": "# IND.2.10.1\n\n**Name:** Интегральный индекс агентности\n**Name (EN):** Integral agency index\n**Type:** scale\n**Format:** float\n**Unit:** 0-100\n**Description:** Агрегированный показатель из групп 2.1-2.3\n\n## Flags\n- for_prompts: true\n- for_qualification: true\n- trainee_model: false\n",
        "02_Готовность к следующей ступени": "# IND.2.10.2\n\n**Name:** Готовность к следующей ступени\n**Name (EN):** Readiness for next stage\n**Type:** scale\n**Format:** float\n**Unit:** percent\n**Description:** Процент выполнения критериев следующей ступени\n\n## Flags\n- for_prompts: true\n- for_qualification: true\n- trainee_model: false\n",
        "03_Профиль сильных сторон": "# IND.2.10.3\n\n**Name:** Профиль сильных сторон\n**Name (EN):** Strengths profile\n**Type:** semantic\n**Format:** list[string]\n**Description:** Области с наивысшими показателями\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: false\n",
        "04_Профиль зон развития": "# IND.2.10.4\n\n**Name:** Профиль зон развития\n**Name (EN):** Growth areas profile\n**Type:** semantic\n**Format:** list[string]\n**Description:** Области требующие внимания\n\n## Flags\n- for_prompts: true\n- for_qualification: false\n- trainee_model: false\n"
      }
    }
  ],
  "rootFiles": {
    "degrees": "# Degrees (Степени квалификации)\n\nVersion: 0.3\n\nСтепени квалификации МИМ (Мастерской инженеров-менеджеров)\n\n## Degrees List\n\n### DEG.Freshman\n- **Name:** Первокурсник\n- **Order:** 0\n- **Description:** Поступил на первый курс, но ещё не закончил его\n\n### DEG.Student\n- **Name:** Ученик\n- **Order:** 1\n- **Description:** Демонстрирует ежедневный слот саморазвития и инвестирует более 10 часов в неделю\n\n### DEG.Worker\n- **Name:** Работник\n- **Order:** 2\n- **Description:** Показывает рациональную работу в логике целей организации с фокусом на ключевых объектах предметной области\n\n### DEG.Strategist\n- **Name:** Стратег\n- **Order:** 3\n- **Description:** Проявляет выбор метода и предмета работ при неопределённости, применяя системное мышление\n\n### DEG.Specialist\n- **Name:** Специалист\n- **Order:** 4\n- **Description:** Демонстрирует понимание обобщённого инженерного процесса и разделения труда, освоение руководств инженерной серии\n\n### DEG.Practitioner\n- **Name:** Практик\n- **Order:** 5\n- **Description:** Показывает изменение собственной культуры работы и организацию до 10 человек\n\n### DEG.Master\n- **Name:** Мастер\n- **Order:** 6\n- **Description:** Инициирует и проводит проекты организационного развития в масштабе компании, добиваясь заметного изменения поведения сотрудников\n\n### DEG.Reformer\n- **Name:** Реформатор\n- **Order:** 7\n- **Description:** Масштабирует мастерство до изменения культуры работы за пределами одного предприятия — на отрасли и сообщества\n\n### DEG.PublicFigure\n- **Name:** Общественный деятель\n- **Order:** 8\n- **Description:** Вносит вклад цивилизационного масштаба, создавая системы мирового значения\n",
    "stages": "# Stages (Ступени)\n\nVersion: 0.3\n\nСтупени внутри Степени квалификации «Ученик» (DEG.Student)\n\n## Stages List\n\n### STG.Student.Random\n- **Name:** Случайный\n- **Duration:** undefined weeks\n- **Description:** Начальная ступень без устойчивого учебного ритма\n\n### STG.Student.Practicing\n- **Name:** Практикующий\n- **Duration:** undefined weeks\n- **Description:** Регулярная практика с минимальными требованиями\n\n### STG.Student.Systematic\n- **Name:** Систематический\n- **Duration:** undefined weeks\n- **Description:** Систематическое обучение с рефлексией\n\n### STG.Student.Disciplined\n- **Name:** Дисциплинированный\n- **Duration:** undefined weeks\n- **Description:** Высокая дисциплина и устойчивые привычки\n\n### STG.Student.Proactive\n- **Name:** Проактивный\n- **Duration:** undefined weeks\n- **Description:** Максимальная вовлечённость и проактивность\n"
  }
};

// Helper to get group by name
export function getGroup(name) {
  return METAMODEL.groups.find(g => g.name === name);
}

// Helper to get indicator content
export function getIndicator(groupName, indicatorName) {
  const group = getGroup(groupName);
  if (!group) return null;
  return group.indicators[indicatorName] || null;
}

// Helper to list all groups
export function listGroups() {
  return METAMODEL.groups.map(g => ({
    name: g.name,
    indicatorCount: Object.keys(g.indicators).length
  }));
}
